arb-dir: lib/core/l10n/arb
template-arb-file: app_en.arb
output-dir: lib/core/l10n/generated
output-localization-file: app_localizations.dart
output-class: AppLocalizations
synthetic-package: false
nullable-getter: false
preferred-supported-locales: [en, es]
untranslated-messages-file: lib/core/l10n/untranslated.csv