name: pokedex_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Core
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0

  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # Routing
  go_router: ^13.0.1

  # Network
  dio: ^5.4.0

  # Data Classes & Serialization
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # Internationalization
  intl: ^0.20.2

  # Local Persistence
  shared_preferences: ^2.2.2

  # UI Helpers
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0
  flutter_svg: ^2.0.10+1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  mocktail: ^1.0.3

  # Code Generation
  build_runner: ^2.4.8
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.9

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/pokeball.png
    - assets/icons/types/

